@baseURL = http://127.0.0.1:3000
@path = api/v1

@docId = Hw5wfueKJIB4UmZb

### get all documents

GET {{baseURL}}/{{path}}/documents 

### get all tags

GET {{baseURL}}/{{path}}/tags 

### Get content of a document by Id

GET {{baseURL}}/{{path}}/documents/{{docId}}/content

### Get Single Document by Id

GET {{baseURL}}/{{path}}/documents/{{docId}}

### Get tags from a Document by Id

GET {{baseURL}}/{{path}}/documents/{{docId}}/tags

### Get tags from a Document by Id

PUT {{baseURL}}/{{path}}/documents/{{docId}}/tags
Content-Type: application/json

[
    { "name" : "NEW_A23"
    },
    { "name" : "NEW_B23"
    }
]

### create document

POST {{baseURL}}/{{path}}/documents
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags"

[ { "name" : "111"}, { "name" : "222"}, { "name" : "333"}]
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

document Name 2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"; filename="image-1.jpg"
Content-Type: image/jpeg

< ../api/documents/content-file/image-1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### delete a document by id

DELETE {{baseURL}}/{{path}}/documents/{{docId}}

### delete All (not available)

DELETE {{baseURL}}/{{path}}/documents