@baseURL = http://127.0.0.1:3000
@path = api/v1

### list all tags

GET {{baseURL}}/{{path}}/tags 

### create 2 tags

POST {{baseURL}}/{{path}}/tags
Content-Type: application/json

[{
    "name" : "___AzzAssszA"
},
{
    "nazme" : "Tzz2s"
}
]

### create a single tag 

POST {{baseURL}}/{{path}}/tags
Content-Type: application/json

{
    "name" : "tagName 1"
}

###

GET {{baseURL}}/{{path}}/tags/7YdaPPzGvLDAubJV

###


DELETE {{baseURL}}/{{path}}/tags/1

