@baseURL = http://127.0.0.1:3000
@path = api/v1

###

GET {{baseURL}}/{{path}}/tags 

###

POST {{baseURL}}/{{path}}/tags
Content-Type: application/json

[{
    "name" : "AAsA"
},
{
    "name" : "T2"
}
]

###

POST {{baseURL}}/{{path}}/tags
Content-Type: application/json

{
    "name" : "tagName 1"
}

###

GET {{baseURL}}/{{path}}/tags/3CFZsqjAskTxL2lL

###


DELETE {{baseURL}}/{{path}}/tags/3CFZsqjAskTxL2lL

