@baseURL = http://127.0.0.1:3000
@path = api/v1

###

GET {{baseURL}}/{{path}}/tags 

###

POST {{baseURL}}/{{path}}/tags
Content-Type: application/json

[{
    "name" : "tagName 1"
},
{
    "name" : "tagName 2"
}
]
###
